# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcruzestefania',
            old_name='numeroDeReporte',
            new_name='numero_de_reporte',
        ),
        migrations.RenameField(
            model_name='modelcruzestefania',
            old_name='reporteDeAlguien',
            new_name='reporte_de_alguien',
        ),
    ]
